export const tailwindColors = {
  // Button colors
  button: {
    primary: {
      'foreground-rest': 'var(--button-primary-fgColor-rest)',
      'foreground-disabled': 'var(--button-primary-fgColor-disabled)',
      'icon-rest': 'var(--button-primary-iconColor-rest)',
      'background-rest': 'var(--button-primary-bgColor-rest)',
      'background-hover': 'var(--button-primary-bgColor-hover)',
      'background-active': 'var(--button-primary-bgColor-active)',
      'background-disabled': 'var(--button-primary-bgColor-disabled)',
      'border-rest': 'var(--button-primary-borderColor-rest)',
      'border-hover': 'var(--button-primary-borderColor-hover)',
      'border-active': 'var(--button-primary-borderColor-active)',
      'border-disabled': 'var(--button-primary-borderColor-disabled)',
      'shadow-selected': 'var(--button-primary-shadow-selected)',
    },
    ghost: {
      'foreground-rest': 'var(--button-ghost-fgColor-rest)',
      'foreground-hover': 'var(--button-ghost-fgColor-hover)',
      'foreground-disabled': 'var(--button-ghost-fgColor-disabled)',
      'icon-rest': 'var(--button-ghost-iconColor-rest)',
      'icon-hover': 'var(--button-ghost-iconColor-hover)',
      'icon-disabled': 'var(--button-ghost-iconColor-disabled)',
      'background-rest': 'var(--button-ghost-bgColor-rest)',
      'background-hover': 'var(--button-ghost-bgColor-hover)',
      'background-active': 'var(--button-ghost-bgColor-active)',
      'background-disabled': 'var(--button-ghost-bgColor-disabled)',
      'border-rest': 'var(--button-ghost-borderColor-rest)',
      'border-hover': 'var(--button-ghost-borderColor-hover)',
      'border-disabled': 'var(--button-ghost-borderColor-disabled)',
    },
    secondary: {
      'foreground-rest': 'var(--button-secondary-fgColor-rest)',
      'foreground-hover': 'var(--button-secondary-fgColor-hover)',
      'foreground-active': 'var(--button-secondary-fgColor-active)',
      'foreground-disabled': 'var(--button-secondary-fgColor-disabled)',
      'background-rest': 'var(--button-secondary-bgColor-rest)',
      'background-hover': 'var(--button-secondary-bgColor-hover)',
      'background-active': 'var(--button-secondary-bgColor-active)',
      'background-disabled': 'var(--button-secondary-bgColor-disabled)',
      'border-rest': 'var(--button-secondary-borderColor-rest)',
      'border-hover': 'var(--button-secondary-borderColor-hover)',
      'border-active': 'var(--button-secondary-borderColor-active)',
      'shadow-selected': 'var(--button-secondary-shadow-selected)',
    },
    danger: {
      'foreground-rest': 'var(--button-danger-fgColor-rest)',
      'foreground-hover': 'var(--button-danger-fgColor-hover)',
      'foreground-active': 'var(--button-danger-fgColor-active)',
      'foreground-disabled': 'var(--button-danger-fgColor-disabled)',
      'icon-rest': 'var(--button-danger-iconColor-rest)',
      'icon-hover': 'var(--button-danger-iconColor-hover)',
      'background-rest': 'var(--button-danger-bgColor-rest)',
      'background-hover': 'var(--button-danger-bgColor-hover)',
      'background-active': 'var(--button-danger-bgColor-active)',
      'background-disabled': 'var(--button-danger-bgColor-disabled)',
      'border-rest': 'var(--button-danger-borderColor-rest)',
      'border-hover': 'var(--button-danger-borderColor-hover)',
      'border-active': 'var(--button-danger-borderColor-active)',
      'shadow-selected': 'var(--button-danger-shadow-selected)',
    },
    inactive: {
      foreground: 'var(--button-inactive-fgColor)',
      background: 'var(--button-inactive-bgColor)',
    },
  },

  // General foreground colors
  foreground: {
    default: 'var(--fgColor-default)',
    muted: 'var(--fgColor-muted)',
    'on-emphasis': 'var(--fgColor-onEmphasis)',
    white: 'var(--fgColor-white)',
    black: 'var(--fgColor-black)',
    disabled: 'var(--fgColor-disabled)',
    link: 'var(--fgColor-link)',
    neutral: 'var(--fgColor-neutral)',
    accent: 'var(--fgColor-accent)',
    success: 'var(--fgColor-success)',
    attention: 'var(--fgColor-attention)',
    severe: 'var(--fgColor-severe)',
    danger: 'var(--fgColor-danger)',
  },

  // General background colors
  background: {
    default: 'var(--bgColor-default)',
    muted: 'var(--bgColor-muted)',
    inset: 'var(--bgColor-inset)',
    emphasis: 'var(--bgColor-emphasis)',
    inverse: 'var(--bgColor-inverse)',
    white: 'var(--bgColor-white)',
    black: 'var(--bgColor-black)',
    disabled: 'var(--bgColor-disabled)',
    transparent: 'var(--bgColor-transparent)',

    'accent-muted': 'var(--bgColor-accent-muted)',
    'accent-emphasis': 'var(--bgColor-accent-emphasis)',
    'success-muted': 'var(--bgColor-success-muted)',
    'success-emphasis': 'var(--bgColor-success-emphasis)',
    'attention-muted': 'var(--bgColor-attention-muted)',
    'attention-emphasis': 'var(--bgColor-attention-emphasis)',
    'severe-muted': 'var(--bgColor-severe-muted)',
    'severe-emphasis': 'var(--bgColor-severe-emphasis)',
    'danger-muted': 'var(--bgColor-danger-muted)',
    'danger-emphasis': 'var(--bgColor-danger-emphasis)',
  },

  // General border colors
  border: {
    default: 'var(--borderColor-default)',
    muted: 'var(--borderColor-muted)',
    emphasis: 'var(--borderColor-emphasis)',
    disabled: 'var(--borderColor-disabled)',
    transparent: 'var(--borderColor-transparent)',
    'accent-muted': 'var(--borderColor-accent-muted)',
    'accent-emphasis': 'var(--borderColor-accent-emphasis)',
    'success-muted': 'var(--borderColor-success-muted)',
    'success-emphasis': 'var(--borderColor-success-emphasis)',
    'attention-muted': 'var(--borderColor-attention-muted)',
    'attention-emphasis': 'var(--borderColor-attention-emphasis)',
    'severe-muted': 'var(--borderColor-severe-muted)',
    'severe-emphasis': 'var(--borderColor-severe-emphasis)',
    'danger-muted': 'var(--borderColor-danger-muted)',
    'danger-emphasis': 'var(--borderColor-danger-emphasis)',
  },

  // Control states
  control: {
    'background-rest': 'var(--control-bgColor-rest)',
    'background-hover': 'var(--control-bgColor-hover)',
    'background-active': 'var(--control-bgColor-active)',
    'background-disabled': 'var(--control-bgColor-disabled)',
    'background-selected': 'var(--control-bgColor-selected)',
    'foreground-rest': 'var(--control-fgColor-rest)',
    'foreground-placeholder': 'var(--control-fgColor-placeholder)',
    'foreground-disabled': 'var(--control-fgColor-disabled)',
    'foreground-selected': 'var(--control-fgColor-selected)',
    'border-rest': 'var(--control-borderColor-rest)',
    'border-emphasis': 'var(--control-borderColor-emphasis)',
    'border-disabled': 'var(--control-borderColor-disabled)',
    'border-selected': 'var(--control-borderColor-selected)',
    'border-success': 'var(--control-borderColor-success)',
    'border-danger': 'var(--control-borderColor-danger)',
    'border-warning': 'var(--control-borderColor-warning)',
    'danger-foreground-rest': 'var(--control-danger-fgColor-rest)',
    'danger-foreground-hover': 'var(--control-danger-fgColor-hover)',
    'danger-background-hover': 'var(--control-danger-bgColor-hover)',
    'danger-background-active': 'var(--control-danger-bgColor-active)',
    'checked-background-rest': 'var(--control-checked-bgColor-rest)',
    'checked-background-hover': 'var(--control-checked-bgColor-hover)',
    'checked-background-active': 'var(--control-checked-bgColor-active)',
    'checked-background-disabled': 'var(--control-checked-bgColor-disabled)',
    'checked-foreground-rest': 'var(--control-checked-fgColor-rest)',
    'checked-foreground-disabled': 'var(--control-checked-fgColor-disabled)',
    'checked-border-rest': 'var(--control-checked-borderColor-rest)',
    'checked-border-hover': 'var(--control-checked-borderColor-hover)',
    'checked-border-active': 'var(--control-checked-borderColor-active)',
    'checked-border-disabled': 'var(--control-checked-borderColor-disabled)',
  },

  textfield: {
    'background-rest': 'var(--textfield-bgColor-rest)',
    'background-hover': 'var(--textfield-bgColor-hover)',
    'background-active': 'var(--textfield-bgColor-active)',
    'background-disabled': 'var(--textfield-bgColor-disabled)',
    'background-selected': 'var(--textfield-bgColor-selected)',
    'foreground-rest': 'var(--textfield-fgColor-rest)',
    'foreground-placeholder': 'var(--textfield-fgColor-placeholder)',
    'foreground-disabled': 'var(--textfield-fgColor-disabled)',
    'foreground-selected': 'var(--textfield-fgColor-selected)',
    'border-rest': 'var(--textfield-borderColor-rest)',
    'border-emphasis': 'var(--textfield-borderColor-emphasis)',
    'border-disabled': 'var(--textfield-borderColor-disabled)',
    'border-selected': 'var(--textfield-borderColor-selected)',
    'border-success': 'var(--textfield-borderColor-success)',
    'border-danger': 'var(--textfield-borderColor-danger)',
    'border-warning': 'var(--textfield-borderColor-warning)',
    'danger-foreground-rest': 'var(--textfield-danger-fgColor-rest)',
    'danger-foreground-hover': 'var(--textfield-danger-fgColor-hover)',
    'danger-background-hover': 'var(--textfield-danger-bgColor-hover)',
    'danger-background-active': 'var(--textfield-danger-bgColor-active)',
  },
};
